import { composeNextState } from '@openfn/language-common';
import {
  request as commonRequest,
  makeBasicAuthHeader,
  assertRelativeUrl,
  logResponse,
  throwError
} from '@openfn/language-common/util';

import nodepath from 'node:path';
import readline from 'node:readline';
import { Readable } from 'node:stream';
import zlib from 'node:zlib';

/**
 * @interface RequestConfig - state configuration passed to the request
 */
export interface RequestConfig {
    apiPath?: string;
    baseUrl?: string;
    username?: string;
    password?: string;
    access_token?: string;
    tls?: Record<string, any>;
}
/**
 * @interface RequestOptions - Options passed to the HTTP request
 */
export interface RequestOptions {
  headers?: Record<string, string>;
  body?: any;
  query?: Record<string, string>;
  tls?: Record<string, any>;
  errors?: Record<number, string | false>;
  timeout?: number;
  parseAs?: 'auto' | 'json' | 'text' | 'stream' | 'base64';
  maxRedirections?: number;
  auth?: boolean
};

/**
 * File items generated by the FHIR server
 * @interface ExportFile
 */
export interface ExportFile {
  type: string;
  url: string;
  count?: number;
}
/**
 * @interface PollOptions - FHIR bulk export polling options
 */
export interface PollOptions extends RequestOptions{
  /** 
   * Milliseconds between status polls when the server sends no `Retry-After`. Default 5000. 
  */
  pollInterval?: number;
  /** 
   * Waiting time in milliseconds. Default 1800000 (30 minutes). 
   */
  pollTimeout?: number;
  /** 
   * Only download files of these resource types. Default: all. 
   */
  types?: string[];
  /** 
   * Stop after this many resources. 
   * Everything downloaded is held in state, so cap large exports. 
   */
  max?: number;
  /** 
   * Also download the server's error files into `state.issues`. Default true. 
   * 
   */
  includeErrors?: boolean;
   /**
   * Buffer resources into an OpenFn Collection instead of holding them in state.
   * Pass a collection name, or `true` for a name derived from the export.
   */
  collection?: string | boolean;
  /** 
   * Resources per write to the Collection. Default 500. 
   */
  batchSize?: number;
  /**
   * Enable streaming data to s3 bucket
   */
  s3?: boolean
}

/**
 * @interface CollectResult - Result for collect request
 */
export type CollectResult = {
  /** 
   * The resources, when buffering is off. Empty when they went to a Collection. 
   */
  resources: any[];
  /** 
   * OperationOutcomes for records the server could not export. 
   */
  issues: any[];
  /** 
   * The Collection the resources were written to, when buffering is on. 
   */
  collection?: string;
  /** How many resources were downloaded 
   * 
  */
  count: number;
};
/**
 * The manifest returned the FHIR server
 * @interface ExportManifest
 * @link https://build.fhir.org/ig/HL7/bulk-data/en/async.html#response---output-manifest
 */
export interface ExportManifest {
  transactionTime: string;
  request: string;
  requiresAccessToken: boolean;
  output: ExportFile[];
  error: ExportFile[];
  deleted?: ExportFile[];
}
/**
 * @interface ManifestResponse - Collect request response
 */
export interface ManifestResponse {
  response: any;
  manifest: ExportManifest;
}

export const prepareNextState = (state: any, response: any) => {
  const { body, ...responseWithoutBody } = response;

  if (!state.references) {
    state.references = [];
  }

  return {
    ...composeNextState(state, response.body),
    response: responseWithoutBody,
  };
};

/**
 * The authenticate function ensures that the request is authenticated
 * @param { RequestConfig } configuration - configuration schema
 * @param { RequestOptions } options - request options
 * @returns headers
 */
export const authenticate = (
  configuration: RequestConfig = {}, 
  options: RequestOptions = {}
) =>{
  const {
    username,
    password
  } = configuration;

  const { headers = {} } = options;

  if(headers?.Authorization){
    return headers;
  }
  if(username && password){
    return ({
      ...headers, 
      Authorization: makeBasicAuthHeader(username, password)
    });
  }
}
/**
 * This helper request function will call out to the FHIR server
 * and add authorisation headers
 * Refer to the common request function for options and details
 * @private
 * @function
 * @param { string } method - The request HTTP method e.g 'GET', 'POST'
 * @param { path } path - The url path e.g '/baseR4'
 * @param { RequestConfig } configuration - configuration schema
 * @param { RequestOptions } options - request options
 * @returns Operation
 */ 
export const request = (
  method: string, 
  path: string,
  configuration: RequestConfig = {}, 
  options: RequestOptions = {}
) => {
  // Check that the path is not an absolute URL before
  // appending credentials commonRequest will do this for you if you
  // pass a baseURL to it and you don't need to build a path here
  assertRelativeUrl(path);

  const { baseUrl, apiPath } = configuration;
  const headers = authenticate(configuration, options);

  // TODO You can define custom error messages here
  //      The request function will throw if it receives
  //      an error code (<=400), terminating the workflow
  const errors = {
    404: 'FHIR resource not found',
  };

  const opts = {
    // Force the response to be parsed as JSON
    parseAs: 'json',

    // Include the error map
    errors,

    // Set the baseUrl from the config object
    baseUrl,

    ...options,

    // You can add extra headers here if you want to
    headers: {
      'content-type': 'application/fhir+json',
      ...headers,
      Prefer: 'respond-async',
    },
  };

  // TODO you may want to add a prefix to the path
  // use path.join to build the path safely
  const safePath = nodepath.join(apiPath ?? '',path);

  // Make the actual request
  return commonRequest(method, safePath, opts).then(logResponse);
};

/**
 * This helper request function will call out to the FHIR server
 * and add authorisation headers
 * Refer to the common request function for options and details
 * @private
 * @function
 * @param { string } method - The request HTTP method e.g 'GET', 'POST'
 * @param { path } path - The url path e.g '/baseR4'
 * @param { RequestConfig } configuration - configuration schema
 * @param { RequestOptions } options - request options
 * @returns Operation
 */ 
export const absoluteRequest = (
  method: string, 
  url: string,
  configuration: RequestConfig = {}, 
  options: RequestOptions = {}
) => {

  const headers = authenticate(configuration, options);

  // TODO You can define custom error messages here
  //      The request function will throw if it receives
  //      an error code (<=400), terminating the workflow
  const errors = {
    404: 'FHIR resource not found',
  };

  const opts = {
    // Force the response to be parsed as JSON
    parseAs: 'json',

    // Include the error map
    errors,

    // Set the baseUrl from the config object
    baseUrl: url,

    ...options,

    // You can add extra headers here if you want to
    headers: {
      'content-type': 'application/fhir+json',
      ...headers
      
    },
  };

  // Make the actual request
  return commonRequest(method, url, opts);
};


/**
 * Low-level Async Generator to stream an individual FHIR NDJSON file line by line
 * @private
 * @function
 * @param { any } stream 
 * @param {string} url 
 * @returns void
 */
// TODO write a unit test and fix type for stream
export const parseNdJson = async function* (stream: any | AsyncIterable<Uint8Array<ArrayBufferLike>>, url: string = '',gzip:boolean = false) {

  let input = toNodeStream(stream, url);
  if (gzip) input = input.pipe(zlib.createGunzip());
  const lineReader = readline.createInterface({
    input: toNodeStream(stream, url),
    crlfDelay: Infinity,
  });
   let lineNumber = 0;

  for await (const rawLine of lineReader) {
    lineNumber++;
    const line = lineNumber === 1 ? rawLine.replace(/^\uFEFF/, '') : rawLine;
    if (!line.trim()) continue;

    try {
      yield JSON.parse(line);
    } 
    catch (err: any) {
      throwError('FILE_PARSING_FAILED',{
        description: "Failed to parse FHIR NDJSON file during bulk export",
        fix: 'Check if the file is encoded as FHIR NDJSON',
        cause: err
      })
    }
  }
}

/**
 * Unwrap a FHIR Binary resource and read the NDJSON inside it.
 * @param {any} response - Http response from FHIR bulk $export
 * @param {ExportFile} file - File resource from FHIR bulk $export stream
 * @returns AsyncGenerator
 */
export const readBinaryResource = async function* (response: any, file: ExportFile) {
 
  const chunks: Buffer[] | any = [];
  for await (const chunk of response.body) chunks.push(Buffer.from(chunk));
  const text = Buffer.concat(chunks).toString('utf8');
 
  let resource: any;
  try {
    resource = JSON.parse(text);
  } catch (error: any) {
    return throwError('UNEXPECTED_EXPORT_FORMAT', {
      description: `${file.url} returned neither NDJSON nor a FHIR resource`,
      fix: 'Check _outputFormat=application/fhir+ndjson and the Accept header on the file request',
      url: file.url,
      body: text.slice(0, 200),
      cause: error,
    });
  }
 
  if (resource?.resourceType === 'OperationOutcome') {
    return throwError('EXPORT_FILE_ERROR', {
      description: `${file.url} returned an OperationOutcome: ${resource.issue?.[0]?.diagnostics ?? 'no diagnostics'}`,
      fix: 'The export file may have expired. Re-run the export.',
      url: file.url,
      outcome: resource,
    });
  }
 
  if (resource?.resourceType !== 'Binary' || typeof resource.data !== 'string') {
    return throwError('UNEXPECTED_EXPORT_FORMAT', {
      description: `${file.url} returned a ${resource?.resourceType ?? 'non-FHIR'} resource, not NDJSON`,
      fix: 'Check that the manifest URLs point at export files',
      url: file.url,
    });
  }
 
  const bytes = Buffer.from(resource.data, 'base64');
  const gzip = /gzip/i.test(resource.contentType ?? '');
  yield* parseNdJson(Readable.from([bytes]), file.url, gzip);
};

/**
 * Validate the manifest from FHIR server
 * @private
 * @function
 * @param {any} response
 * @param {string} url - The url for downloading NDJSON file from FHIR server
 * @returns Object
 */
export const toManifest = (response: any, url: string): ManifestResponse => {
  const { body } = response || {};
  if (!body || !Array.isArray(body.output)) {
    return throwError('INVALID_MANIFEST', {
      description: `The export status at ${url} did not return a manifest with an "output" array`,
      fix: 'Check that the FHIR server implements Bulk Data $export',
      url,
      body,
    });
  }
 
  const files = (value: any): ExportFile[] =>
    (Array.isArray(value) ? value : [])
      .filter(entry => entry && typeof entry.url === 'string')
      .map(entry => ({
        type: typeof entry.type === 'string' ? entry.type : 'unknown',
        url: entry.url,
        ...(typeof entry.count === 'number' ? { count: entry.count } : {}),
      }));
 
  return ({
    manifest: {
      transactionTime: body.transactionTime ?? '',
      request: body.request ?? url,
      requiresAccessToken: body.requiresAccessToken === true,
      output: files(body.output),
      error: files(body.error),
      ...(body.deleted ? { deleted: files(body.deleted) } : { deleted: []}),
    },
    response
    }
  )
}

/**
 * The sleep function pauses the job
 * @private
 * @function
 * @param { number } ms - Number of milliseconds to pause
 * @returns void
 */
export const sleep = (ms: number): Promise<void> => {
  return new Promise(resolve => setTimeout(resolve, ms));
}
/**
 * Convert FHIR _since date to ISO format
 * @private
 * @function
 * @param {string | Date} value - The _since parameter
 * @returns string
 */
// TODO use openFn dateFns utility
export const toIsoFormat = (value: string | Date): string => {
  return value instanceof Date ? value.toISOString() : value;
}
/**
 * Save files to AWS s3
 * @param {string} bucket - AWS s3 bucket
 * @param {ExportFile} file - File being streamed
 * @returns void 
 */
export const streamFileToS3 =(bucket: string, file: ExportFile)=>{
  /*put({
      bucket, 
      key: file.url
  })
      */
}
/**
 * Convert the file stream to Readable
 * @param {any} source - File Stream
 * @param {string} url - File url representing the stream
 * @returns Readable 
 */
export const toNodeStream = (source: any, url: string): Readable => {
  if (typeof source === 'string' || Buffer.isBuffer(source)) return Readable.from([source]);
 
  if (source instanceof Readable) return source;
  if (typeof source?.on === 'function' && typeof source?.pipe === 'function') return source;
 
  if (typeof source?.getReader === 'function') return Readable.fromWeb(source);
 
  if (typeof source?.[Symbol.asyncIterator] === 'function') return Readable.from(source);
 
  return throwError('INVALID_NDJSON_SOURCE', {
    description: `Cannot read NDJSON from a ${describe(source)}${url ? ` (${url})` : ''}`,
    fix:
      'Pass the response body, not state: streamNdJsonFile(state, file, manifest, options). ' +
      "If you are calling request() yourself, set parseAs: 'stream'.",
    url,
  });
};
 
const describe = (value: any): string => {
  if (value === null || value === undefined) return String(value);
  if (value?.configuration || value?.data) return 'state object';
  return Array.isArray(value) ? 'array' : typeof value;
};
